// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.CypherQuerySource.ExecuteQueryAsync(OrchardCore.Queries.Query,System.Collections.Generic.IDictionary{System.String,System.Object})~System.Threading.Tasks.Task{OrchardCore.Queries.IQueryResults}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S927:parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.CypherQueryDisplayDriver.Display(DFC.ServiceTaxonomy.Cypher.Models.CypherQuery,OrchardCore.DisplayManagement.ModelBinding.IUpdateModel)~OrchardCore.DisplayManagement.Views.IDisplayResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S927:parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.CypherQueryDisplayDriver.Edit(DFC.ServiceTaxonomy.Cypher.Models.CypherQuery,OrchardCore.DisplayManagement.ModelBinding.IUpdateModel)~OrchardCore.DisplayManagement.Views.IDisplayResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S927:parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.Drivers.CypherQueryDisplayDriver.Display(DFC.ServiceTaxonomy.Cypher.Models.CypherQuery,OrchardCore.DisplayManagement.ModelBinding.IUpdateModel)~OrchardCore.DisplayManagement.Views.IDisplayResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S927:parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.Drivers.CypherQueryDisplayDriver.Edit(DFC.ServiceTaxonomy.Cypher.Models.CypherQuery,OrchardCore.DisplayManagement.ModelBinding.IUpdateModel)~OrchardCore.DisplayManagement.Views.IDisplayResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:DFC.ServiceTaxonomy.Cypher.Drivers.CypherQueryDisplayDriver.S")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:DFC.ServiceTaxonomy.Cypher.Menus.AdminMenu.S")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.Helpers.Neo4JHelper.GetListOfRecordsAsync~System.Threading.Tasks.Task{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "<Pending>", Scope = "member", Target = "~M:DFC.ServiceTaxonomy.Cypher.Helpers.Neo4JHelper.#ctor(DFC.ServiceTaxonomy.Cypher.Configuration.Neo4jConfiguration)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:DFC.ServiceTaxonomy.Cypher.CypherQuerySource.neo4JHelper")]
