// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("DFC_GDSCombinations")]
    public partial class DfcGdscombination
    {
        [Required]
        [Column("onet_element_one_id")]
        [StringLength(20)]
        public string OnetElementOneId { get; set; }
        [Required]
        [Column("onet_element_two_id")]
        [StringLength(20)]
        public string OnetElementTwoId { get; set; }
        [Key]
        [Column("combined_element_id")]
        [StringLength(20)]
        public string CombinedElementId { get; set; }
        [Column("element_name")]
        [StringLength(150)]
        public string ElementName { get; set; }
        [Column("description")]
        [StringLength(1500)]
        public string Description { get; set; }
        [Column("application_order")]
        public short? ApplicationOrder { get; set; }
        [Column("datetimestamp", TypeName = "datetime")]
        public DateTime Datetimestamp { get; set; }
    }
}
