// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("DFC_SocMappings")]
    public partial class DfcSocMapping
    {
        [Required]
        [StringLength(200)]
        public string JobProfile { get; set; }
        [Key]
        [StringLength(10)]
        public string SocCode { get; set; }
        [Column("ONetCode")]
        [StringLength(10)]
        public string OnetCode { get; set; }
        public int QualityRating { get; set; }
        [StringLength(20)]
        public string UpdateStatus { get; set; }
    }
}
