// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("emerging_tasks")]
    public partial class EmergingTask
    {
        [Required]
        [Column("onetsoc_code")]
        [StringLength(10)]
        public string OnetsocCode { get; set; }
        [Required]
        [Column("task")]
        [StringLength(1000)]
        public string Task { get; set; }
        [Required]
        [Column("category")]
        [StringLength(8)]
        public string Category { get; set; }
        [Column("original_task_id", TypeName = "decimal(8, 0)")]
        public decimal? OriginalTaskId { get; set; }
        [Column("writein_total", TypeName = "decimal(3, 0)")]
        public decimal WriteinTotal { get; set; }
        [Column("date_updated", TypeName = "date")]
        public DateTime DateUpdated { get; set; }
        [Required]
        [Column("domain_source")]
        [StringLength(30)]
        public string DomainSource { get; set; }

        [ForeignKey(nameof(OnetsocCode))]
        public virtual OccupationDatum OnetsocCodeNavigation { get; set; }
        [ForeignKey(nameof(OriginalTaskId))]
        public virtual TaskStatement OriginalTask { get; set; }
    }
}
