// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("green_task_statements")]
    public partial class GreenTaskStatement
    {
        [Required]
        [Column("onetsoc_code")]
        [StringLength(10)]
        public string OnetsocCode { get; set; }
        [Column("task_id", TypeName = "decimal(8, 0)")]
        public decimal TaskId { get; set; }
        [Required]
        [Column("green_task_type")]
        [StringLength(40)]
        public string GreenTaskType { get; set; }

        [ForeignKey(nameof(OnetsocCode))]
        public virtual OccupationDatum OnetsocCodeNavigation { get; set; }
        [ForeignKey(nameof(TaskId))]
        public virtual TaskStatement Task { get; set; }
    }
}
