// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("iwa_reference")]
    public partial class IwaReference
    {
        public IwaReference()
        {
            DwaReferences = new HashSet<DwaReference>();
        }

        [Required]
        [Column("element_id")]
        [StringLength(20)]
        public string ElementId { get; set; }
        [Key]
        [Column("iwa_id")]
        [StringLength(20)]
        public string IwaId { get; set; }
        [Required]
        [Column("iwa_title")]
        [StringLength(150)]
        public string IwaTitle { get; set; }

        [ForeignKey(nameof(ElementId))]
        [InverseProperty(nameof(ContentModelReference.IwaReferences))]
        public virtual ContentModelReference Element { get; set; }
        [InverseProperty(nameof(DwaReference.Iwa))]
        public virtual ICollection<DwaReference> DwaReferences { get; set; }
    }
}
