// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("job_zone_reference")]
    public partial class JobZoneReference
    {
        [Key]
        [Column("job_zone", TypeName = "decimal(1, 0)")]
        public decimal JobZone { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [Column("experience")]
        [StringLength(300)]
        public string Experience { get; set; }
        [Required]
        [Column("education")]
        [StringLength(500)]
        public string Education { get; set; }
        [Required]
        [Column("job_training")]
        [StringLength(300)]
        public string JobTraining { get; set; }
        [Required]
        [Column("examples")]
        [StringLength(500)]
        public string Examples { get; set; }
        [Required]
        [Column("svp_range")]
        [StringLength(25)]
        public string SvpRange { get; set; }
    }
}
