// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("scales_reference")]
    public partial class ScalesReference
    {
        public ScalesReference()
        {
            EteCategories = new HashSet<EteCategory>();
            TaskCategories = new HashSet<TaskCategory>();
            WorkContextCategories = new HashSet<WorkContextCategory>();
        }

        [Key]
        [Column("scale_id")]
        [StringLength(3)]
        public string ScaleId { get; set; }
        [Required]
        [Column("scale_name")]
        [StringLength(50)]
        public string ScaleName { get; set; }
        [Column("minimum", TypeName = "decimal(1, 0)")]
        public decimal Minimum { get; set; }
        [Column("maximum", TypeName = "decimal(3, 0)")]
        public decimal Maximum { get; set; }

        [InverseProperty(nameof(EteCategory.Scale))]
        public virtual ICollection<EteCategory> EteCategories { get; set; }
        [InverseProperty(nameof(TaskCategory.Scale))]
        public virtual ICollection<TaskCategory> TaskCategories { get; set; }
        [InverseProperty(nameof(WorkContextCategory.Scale))]
        public virtual ICollection<WorkContextCategory> WorkContextCategories { get; set; }
    }
}
