// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    public partial class sp_GetInterestsByOnetCodeToDeleteResult
    {
        public string scale_id { get; set; }
        public decimal data_value { get; set; }
        public string element_name { get; set; }
        public string description { get; set; }
    }
}
