// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    public partial class sp_GetToolsTecByOnetCodeToDeleteResult
    {
        public string t2_type { get; set; }
        public string t2_example { get; set; }
        public string onetsoc_code { get; set; }
        public string class_title { get; set; }
    }
}
