// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("task_categories")]
    public partial class TaskCategory
    {
        [Key]
        [Column("scale_id")]
        [StringLength(3)]
        public string ScaleId { get; set; }
        [Key]
        [Column("category", TypeName = "decimal(3, 0)")]
        public decimal Category { get; set; }
        [Required]
        [Column("category_description")]
        [StringLength(1000)]
        public string CategoryDescription { get; set; }

        [ForeignKey(nameof(ScaleId))]
        [InverseProperty(nameof(ScalesReference.TaskCategories))]
        public virtual ScalesReference Scale { get; set; }
    }
}
