// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Module.EFDataModels
{
    [Table("tools_and_technology")]
    public partial class ToolsAndTechnology
    {
        [Required]
        [Column("onetsoc_code")]
        [StringLength(10)]
        public string OnetsocCode { get; set; }
        [Required]
        [Column("t2_type")]
        [StringLength(10)]
        public string T2Type { get; set; }
        [Required]
        [Column("t2_example")]
        [StringLength(150)]
        public string T2Example { get; set; }
        [Column("commodity_code", TypeName = "decimal(8, 0)")]
        public decimal CommodityCode { get; set; }
        [Required]
        [Column("hot_technology")]
        [StringLength(1)]
        public string HotTechnology { get; set; }

        [ForeignKey(nameof(CommodityCode))]
        public virtual UnspscReference CommodityCodeNavigation { get; set; }
        [ForeignKey(nameof(OnetsocCode))]
        public virtual OccupationDatum OnetsocCodeNavigation { get; set; }
    }
}
