parameters:
  - name: DfcServiceTaxonomyTestBranch
    type: string
    default: refs/heads/master

variables:
  SolutionBaseName: 'DFC.ServiceTaxonomy'
  EditorAdminUserEmail: 'careersdevops@education.gov.uk'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.16.0
    endpoint: 'SkillsFundingAgency'

trigger:
  branches:
    include:
      - dev
      - master
  paths:
    exclude:
      - STAXCosmosHostnameReplacement/**

pr:
  branches:
    include:
      - dev
      - master

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  jobs:
  - job: BuildArmTemplates
    displayName: "Build the ARM templates"
    workspace:
      clean: all
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"

    - task: CopyFiles@2
      displayName: 'Copy PSScripts Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: 'PSScripts/**/*.ps1'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Resources/PSScripts'
        flattenFolders: true

    - task: PublishPipelineArtifact@0
      displayName: Publish PSScripts Pipeline Artifact
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Resources/PSScripts"
        artifactName: ${{ variables.SolutionBaseName }}.Editor.Resources.PSScripts

  # - job: BuildDotNet
  #   displayName: "Build the dotnet core applications"
  #   workspace:
  #     clean: all
  #   steps:
  #   - template: StepTemplates/dfc-dotnetcore-build.yml
  #     parameters:
  #       SolutionBaseName: $(SolutionBaseName).Editor
  #       BuildPlatform: 'any cpu'
  #       BuildConfiguration: 'release'
  #   - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
  #     parameters:
  #       SolutionBaseName: $(SolutionBaseName).OrchardCoreInitialiser
  #       BuildPlatform: 'any cpu'
  #       BuildConfiguration: 'release'
  #   - powershell: |
  #       New-Item -Type Directory -Path $(SolutionBaseName).Editor\AppSettingsArtifact\App_Data\Sites\Default\ -Force
  #       Copy-Item -Path $(SolutionBaseName).Editor\App_Data\Sites\Default\appsettings.template.json -Destination $(SolutionBaseName).Editor\AppSettingsArtifact\App_Data\Sites\Default\appsettings.json
  #     displayName: 'PowerShell Script: Copy appsettings.template.json'
  #   - task: PublishPipelineArtifact@1
  #     inputs:
  #       targetPath: $(SolutionBaseName).Editor\AppSettingsArtifact\
  #       artifactName: $(SolutionBaseName).Editor.AppSettings
  #   - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-notests.yml@dfc-devops
  #     parameters:
  #       SolutionBaseName: $(SolutionBaseName).IntegrationTests
  #       BuildPlatform: 'any cpu'
  #       BuildConfiguration: 'release'

  #   - task: NuGetToolInstaller@1
  #     inputs:
  #       versionSpec: '>=5.4.0'

  #   - task: PublishBuildArtifacts@1
  #     displayName: 'Publish media folder'
  #     inputs:
  #       PathtoPublish: 'media'
  #       artifactName: media

- stage: DeployToDevClone
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_CLONE_SERVICETAXONOMY
  variables:
  - group: dfc-shared-all
  - group: dfc-stax-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-dev
  - group: dfc-stax-shared-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  - template: VariableTemplates/SharedEnvironmentVariables.yml
  - template: VariableTemplates/DevCloneEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: DEV_CLONE_SERVICETAXONOMY
      EnvironmentRef: dev
      PackageFile:  "$(Agent.BuildDirectory)/DFC.ServiceTaxonomy.Editor/DeploymentPackages/DFC.ServiceTaxonomy.Editor.zip"
      ArmTemplateFolder: "$(Agent.BuildDirectory)/DFC.ServiceTaxonomy.Editor/Azure/ArmTemplates/"
      Location: 'West Europe'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusinessTag: '$(ParentBusiness)'
      ServiceOfferingTag: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      WebAppName: '$(WebAppName)'
      OrchardCoreUri: 'https://$(WebAppName).azurewebsites.net/'
      EditorAdminUsername: $(OrchardEditorAdminUserName)
      EditorAdminUserEmail: $(EditorAdminUserEmail)
      EditorAdminUserPassword: $(OrchardEditorAdminPassword)
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      DfcServiceTaxonomyTestsBuildId: $(DfcServiceTaxonomyTestsBuildId)
      TestArtifactBranch: ${{ parameters.DfcServiceTaxonomyTestBranch }}
      TestExclusionTag: 'NotDev'
      MediaStorageAccountName: $(MediaStorageAccountName)
      PSScriptPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Editor.Resources.PSScripts"

- stage: DeployToSitClone
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_CLONE_SERVICETAXONOMY
  variables:
  - group: dfc-shared-all
  - group: dfc-stax-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-sit
  - group: dfc-stax-shared-sit
  - group: 'KeyVault - dfc-sit-shared-kv'
  - template: VariableTemplates/SharedEnvironmentVariables.yml
  - template: VariableTemplates/SitCloneEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      Environment: SIT_CLONE_SERVICETAXONOMY
      PackageFile:  "$(Agent.BuildDirectory)/DFC.ServiceTaxonomy.Editor/DeploymentPackages/DFC.ServiceTaxonomy.Editor.zip"
      ArmTemplateFolder: "$(Agent.BuildDirectory)/DFC.ServiceTaxonomy.Editor/Azure/ArmTemplates/"
      Location: 'West Europe'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusinessTag: '$(ParentBusiness)'
      ServiceOfferingTag: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      WebAppName: '$(WebAppName)'
      OrchardCoreUri: 'https://$(WebAppName).azurewebsites.net/'
      EditorAdminUsername: $(OrchardEditorAdminUserName)
      EditorAdminUserEmail: $(EditorAdminUserEmail)
      EditorAdminUserPassword: $(OrchardEditorAdminPassword)
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      DfcServiceTaxonomyTestsBuildId: $(DfcServiceTaxonomyTestsBuildId)
      TestArtifactBranch: ${{ parameters.DfcServiceTaxonomyTestBranch }}
      TestExclusionTag: 'NotSit'
      MediaStorageAccountName: $(MediaStorageAccountName)
      PSScriptPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Editor.Resources.PSScripts"
