parameters:
- name: runMigrationInPreProd
  displayName: Run the migration in Pre-Production?
  type: boolean
  default: false
- name: runMigrationInProd
  displayName: Run the migration in Production?
  type: boolean
  default: false

trigger:  none
pr: none

pool:
  name: NCS - CI and CD

stages:
- stage: Build
  jobs: 
  - job: BuildApplication
    workspace:
      clean: all
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 6'
      inputs:
        version: 6.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: 'STAXCosmosHostnameReplacement/STAXCosmosHostnameReplacement.sln'
        feedsToUse: 'select'
        vstsFeed: 'NationalCareersService'

    - task: DotNetCoreCLI@2
      displayName: 'Publish - dotnet publish application'
      inputs:
        command: 'publish'
        projects: 'STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement.csproj'
        arguments: '--self-contained true -r win-x86 --configuration Debug --output $(build.artifactstagingdirectory)\Artifact'
        publishWebProjects: false 
        zipAfterPublish: false
   
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: STAXCosmosHostnameReplacement'
      inputs:
        pathtoPublish: $(build.artifactstagingdirectory)\Artifact
        artifactName: STAXCosmosHostnameReplacement
        publishLocation: container

- stage: MigratePreProduction
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.runMigrationInPreProd }}', true))
  dependsOn:
  - Build
  variables:
    SearchDomainSuffix: .ase-01.dfc.preprodazure.sfa.bis.gov.uk
  jobs:
  - deployment: MigratePreProduction
    displayName: "Migrate to PreProduction"
    environment: PP_Grafana
    timeoutInMinutes: 300
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzurePowershell@5
            displayName: 'Run migration on pre-production'
            inputs:
              azureSubscription: SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)
              scriptType: InlineScript
              azurePowerShellVersion: LatestVersion
              pwsh: true
              Inline: |
                Write-Host "Getting connection string for dfc-pp-compui-shared-cdb"

                $connStrings = Get-AzCosmosDBAccountKey -ResourceGroupName dfc-pp-compui-shared-rg -Name dfc-pp-compui-shared-cdb -Type "ConnectionStrings" 
                $connectionString = $connStrings["Secondary SQL Connection String"]

                & $(Pipeline.Workspace)\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement.exe --connection-string "$connectionString" --search-domain "${{ variables.SearchDomainSuffix }}" --replacement-domain ".azurewebsites.net"

                Write-Host "Getting connection string for dfc-pp-app-sharedresources-cdb"
                $connStrings = Get-AzCosmosDBAccountKey -ResourceGroupName dfc-pp-app-sharedresources-rg -Name dfc-pp-app-sharedresources-cdb -Type "ConnectionStrings" 
                $connectionString = $connStrings["Secondary SQL Connection String"]

                & $(Pipeline.Workspace)\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement.exe --connection-string "$connectionString" --search-domain "${{ variables.SearchDomainSuffix }}" --replacement-domain ".azurewebsites.net"


- stage: MigrateProduction
  # condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq('${{ parameters.runMigrationInProd }}', true))
  dependsOn:
    - Build
  variables:
    SearchDomainSuffix: .ase-01.dfc.prodazure.sfa.bis.gov.uk
  jobs:
  - deployment: MigrateProduction
    displayName: "Migrate to Production"
    environment: PRD_Grafana
    timeoutInMinutes: 300
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzurePowershell@5
            displayName: 'Run migration on production'
            inputs:
              azureSubscription: SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)
              scriptType: InlineScript
              azurePowerShellVersion: LatestVersion
              pwsh: true
              Inline: |
                Write-Host "Getting connection string for dfc-prd-compui-shared-cdb"

                $connStrings = Get-AzCosmosDBAccountKey -ResourceGroupName dfc-prd-compui-shared-rg -Name dfc-prd-compui-shared-cdb -Type "ConnectionStrings" 
                $connectionString = $connStrings["Secondary SQL Connection String"]

                & $(Pipeline.Workspace)\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement.exe --connection-string "$connectionString" --search-domain "${{ variables.SearchDomainSuffix }}" --replacement-domain ".azurewebsites.net"

                Write-Host "Getting connection string for dfc-prd-app-sharedresources-cdb"
                $connStrings = Get-AzCosmosDBAccountKey -ResourceGroupName dfc-prd-app-sharedresources-rg -Name dfc-prd-app-sharedresources-cdb -Type "ConnectionStrings" 
                $connectionString = $connStrings["Secondary SQL Connection String"]

                & $(Pipeline.Workspace)\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement\STAXCosmosHostnameReplacement.exe --connection-string "$connectionString" --search-domain "${{ variables.SearchDomainSuffix }}" --replacement-domain ".azurewebsites.net"



    