namespace DFC.ServiceTaxonomy.CompUi.Enums
{
    public enum ContentTypes
    {
        ApprenticeshipEntryRequirements,
        ApprenticeshipLink,
        ApprenticeshipRequirements,
        Banner,
        CollegeEntryRequirements,
        CollegeLink,
        CollegeRequirements,
        DigitalSkills,
        DynamicTitlePrefix,
        Environment,
        HiddenAlternativeTitle,
        JobProfile,
        JobProfileCategory,
        JobProfileSector,
        JobProfileSpecialism,
        Location,
        Page,
        Pagebanner,
        PersonalityFilteringQuestion,
        PersonalityQuestionSet,
        PersonalityShortQuestion,
        PersonalityTrait,
        RealStory,
        Registration,
        Restriction,
        SectorLandingPage,
        SharedContent,
        Skill,
        SOCCode,
        SOCSkillsMatrix,
        Taxonomy,
        TriageToolFilter,
        Uniform,
        UniversityEntryRequirements,
        UniversityLink,
        UniversityRequirements,
        WorkingHoursDetail,
        WorkingPatternDetail,
        WorkingPatterns,


    }
}
