variables:
- name: ReleaseEnvironmentName
  value: prd
- name: ResourceGroup
  value: dfc-prd-stax-editor-rg
- name: WebAppName
  value: dfc-prd-stax-editor-as
- name: SqlDatabaseName
  value: dfc-prd-stax-editor-db
- name: OrchardCoreSqlDatabaseConnStr
  value: Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(WebAppName)-svc;Password=$(OrchardEditorSqlUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: EventGridEnabled
  value: true
- name: EventGridTopicSku
  value: basic
- name: PublishToSlack
  value: true
- name: ExceptionCountThreshold
  value: 10
- name: EnableAzureMonitorAlerting
  value: true
- name: JobProfilePublishedAppPrefix
  value: https://nationalcareers.service.gov.uk/job-profiles
- name: JobProfilePreviewAppPrefix
  value: https://draft.nationalcareers.service.gov.uk/job-profiles