variables:
- name: ReleaseEnvironmentName
  value: prd
- name: ResourceGroup
  value: dfc-prd-stax-editor-rg
- name: WebAppName
  value: dfc-prd-stax-editor-as-ver2
- name: SqlDatabaseName
  value: dfc-prd-stax-editor-db
- name: OrchardCoreSqlDatabaseConnStr
  value: Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(WebAppName)-svc;Password=$(OrchardEditorSqlUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: ExceptionCountThreshold
  value: 10
- name: EnableAzureMonitorAlerting
  value: true
- name: PreviewLoginUrl
  value: https://nationalcareers.service.gov.uk/ncspreview
- name: CipherTextValiditySeconds
  value: 60
- name: RedirectUri0
  value: /find-a-course
- name: ContentType0
  value: Header
- name: RedirectUri1
  value: /find-a-course
- name: ContentType1
  value: Footer
