variables:
- name: ReleaseEnvironmentName
  value: prd
- name: ResourceGroup
  value: dfc-prd-stax-editor-rg
- name: WebAppName
  value: dfc-prd-stax-editor-as
- name: SqlDatabaseName
  value: dfc-prd-stax-editor-db
- name: OrchardCoreSqlDatabaseConnStr
  value: Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(WebAppName)-svc;Password=$(OrchardEditorSqlUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: EventGridEnabled
  value: true
- name: EventGridTopicSku
  value: basic
- name: PublishToSlack
  value: true
- name: ServicePrincipalName
  value: $(ServicePrincipalName)
- name: MediaStorageAccountName
  value: $(MediaStorageAccountName)
- name: CdnProfileName
  value: $(CdnProfileName)
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true