variables:
- name: ReleaseEnvironmentName
  value: sit
- name: ResourceGroup
  value: dfc-sit-stax-editor-rg
- name: StorageAccountResourceGroupName
  value: dfc-sit-dig-rg
- name: MediaStorageAccountName
  value: dfcsitdigstr
- name: WebAppName
  value: dfc-sit-stax-editor-as
- name: SqlDatabaseName
  value: dfc-sit-stax-editor-db
- name: OrchardCoreSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(WebAppName)-svc;Password=$(OrchardEditorSqlUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: FunctionalTestsSqlDatabaseConnStr
  value: 'Server=tcp:$(sharedSqlServerName).database.windows.net,1433;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(FunctionalTestsUser);Password=$(FunctionalTestsUserPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
- name: PreviewLoginUrl
  value: https://sit-beta.nationalcareersservice.org.uk/ncspreview
- name: CipherTextValiditySeconds
  value: 60
- name: RedirectUri0
  value: /explore-careers/job-sector
- name: ContentType0
  value: JobProfileSector
- name: RedirectUri1
  value: /job-profiles
- name: ContentType1
  value: JobProfile
- name: RedirectUri2
  value: /
- name: ContentType2
  value: Header
- name: RedirectUri3
  value: /
- name: ContentType3
  value: Footer
- name: BaseUrlPath
  value: https://sit-beta.nationalcareersservice.org.uk

