// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("alternate_titles")]
    public partial class AlternateTitle
    {
        [Required]
        [Column("onetsoc_code")]
        [StringLength(10)]
        public string OnetsocCode { get; set; }
        [Required]
        [Column("alternate_title")]
        [StringLength(250)]
        public string AlternateTitle1 { get; set; }
        [Column("short_title")]
        [StringLength(150)]
        public string ShortTitle { get; set; }
        [Required]
        [Column("sources")]
        [StringLength(50)]
        public string Sources { get; set; }

        [ForeignKey(nameof(OnetsocCode))]
        public virtual OccupationDatum OnetsocCodeNavigation { get; set; }
    }
}