// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("DFC_GDSTranslations_Staging")]
    public partial class DfcGdstranslationsStaging
    {
        [Column("ID")]
        [StringLength(50)]
        public string Id { get; set; }
        [StringLength(50)]
        public string Skill { get; set; }
        [StringLength(300)]
        public string Description { get; set; }
        [StringLength(100)]
        public string Translation { get; set; }
        [Column("column_5")]
        [StringLength(50)]
        public string Column5 { get; set; }
    }
}