// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("DFC_LiveSocsLinkedToJobProfile_Staging")]
    public partial class DfcLiveSocsLinkedToJobProfileStaging
    {
        [StringLength(200)]
        public string Title { get; set; }
        [Column("SOCCode")]
        [StringLength(50)]
        public string Soccode { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
    }
}