// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("DFC_SocMappings_Staging")]
    public partial class DfcSocMappingsStaging
    {
        [StringLength(100)]
        public string Title { get; set; }
        [Column("5_digit_SOC_code")]
        [StringLength(50)]
        public string _5DigitSocCode { get; set; }
        [Column("O_NET_code")]
        [StringLength(50)]
        public string ONetCode { get; set; }
        [Column("column_4")]
        [StringLength(50)]
        public string Column4 { get; set; }
    }
}