// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("ete_categories")]
    public partial class EteCategory
    {
        [Key]
        [Column("element_id")]
        [StringLength(20)]
        public string ElementId { get; set; }
        [Key]
        [Column("scale_id")]
        [StringLength(3)]
        public string ScaleId { get; set; }
        [Key]
        [Column("category", TypeName = "decimal(3, 0)")]
        public decimal Category { get; set; }
        [Required]
        [Column("category_description")]
        [StringLength(1000)]
        public string CategoryDescription { get; set; }

        [ForeignKey(nameof(ElementId))]
        [InverseProperty(nameof(ContentModelReference.EteCategories))]
        public virtual ContentModelReference Element { get; set; }
        [ForeignKey(nameof(ScaleId))]
        [InverseProperty(nameof(ScalesReference.EteCategories))]
        public virtual ScalesReference Scale { get; set; }
    }
}