// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("job_zones")]
    public partial class JobZone
    {
        [Required]
        [Column("onetsoc_code")]
        [StringLength(10)]
        public string OnetsocCode { get; set; }
        [Column("job_zone", TypeName = "decimal(1, 0)")]
        public decimal JobZone1 { get; set; }
        [Column("date_updated", TypeName = "date")]
        public DateTime DateUpdated { get; set; }
        [Required]
        [Column("domain_source")]
        [StringLength(30)]
        public string DomainSource { get; set; }

        [ForeignKey(nameof(JobZone1))]
        public virtual JobZoneReference JobZone1Navigation { get; set; }
        [ForeignKey(nameof(OnetsocCode))]
        public virtual OccupationDatum OnetsocCodeNavigation { get; set; }
    }
}