// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    public partial class sp_GetToolsTecByOnetCodeV2Result
    {
        public int? number { get; set; }
        public string t2_type { get; set; }
        public string class_title { get; set; }
        public string segment_title { get; set; }
    }
}
