// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DFC.ServiceTaxonomy.JobProfiles.Service.EFDataModels
{
    [Table("survey_booklet_locations")]
    public partial class SurveyBookletLocation
    {
        [Required]
        [Column("element_id")]
        [StringLength(20)]
        public string ElementId { get; set; }
        [Required]
        [Column("survey_item_number")]
        [StringLength(4)]
        public string SurveyItemNumber { get; set; }
        [Required]
        [Column("scale_id")]
        [StringLength(3)]
        public string ScaleId { get; set; }

        [ForeignKey(nameof(ElementId))]
        public virtual ContentModelReference Element { get; set; }
        [ForeignKey(nameof(ScaleId))]
        public virtual ScalesReference Scale { get; set; }
    }
}